name: brats19
train_csv_path: /home/dengzhipeng/data/brain_processed/brats19/train.csv
val_csv_path: /home/dengzhipeng/data/brain_processed/brats19/val.csv
test_csv_path: /home/dengzhipeng/data/brain_processed/brats19/test.csv
image_folder: /home/dengzhipeng/data/brain_processed/brats19/h5
