name: nyu
train_csv_path: /home/dengzhipeng/data/mmue_processed/nyu/train.csv
val_csv_path: /home/dengzhipeng/data/mmue_processed/nyu/val.csv
test_csv_path: /home/dengzhipeng/data/mmue_processed/nyu/test.csv
image_folder: /home/dengzhipeng/data/mmue_processed/nyu/h5
