name: nyu
train_csv_path: /home/dengzhipeng/data/mmue/processed_NYU/train.csv
val_csv_path: /home/dengzhipeng/data/mmue/processed_NYU/val.csv
test_csv_path: /home/dengzhipeng/data/mmue/processed_NYU/test.csv
image_folder: /home/dengzhipeng/data/mmue/processed_NYU/h5
