# @package _global_          
# merge this file to global config

dataset:
  task: seg

model:
  in_channels: 4          
  num_classes: 4          
  spatial_dims: 3         
  channels: [32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  norm: "INSTANCE"
  act: "RELU"
  dropout: 0.0

training:
  data:
    transforms:
      normalize: true
      geom_aug: false
      intensity_aug: false
      image_size: [4, 160, 160, 160]
      mean: [0.0, 0.0, 0.0, 0.0]
      std:  [1.0, 1.0, 1.0, 1.0]
      
evaluation:
  per_class: true
  class_names: 
    - background
    - tumor
    - edema
    - enhancing